"""
Materials Science & Crystallography Synthesizer — Generates PyMatGen / ASE Python scripts for VESTA 3D crystal structure analysis.

Supports:
- Generating .CIF crystal structure files
- Computing lattice parameters, density, unit cell volume
- Preparing input files for VESTA visualization / simulation tools
"""
import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)


class MaterialsScienceSynthesizer:
    """
    Synthesizes materials science Python scripts for crystal lattice structure calculations,
    .CIF file generation, and VESTA visualization setups.
    """

    @staticmethod
    def generate_cif_script(formula: str, output_path: str = "structure.cif") -> str:
        """
        Generates a self-contained Python script using PyMatGen/ASE or basic structure math
        to compute lattice volume and output a .CIF structure file.
        """
        # `formula` is embedded TWICE in the generated script, in two
        # different contexts that each need their own safe handling:
        #   1. `formula = "{formula}"` — a Python string literal in the
        #      OUTER generated script. repr() handles any content safely.
        #   2. `data_{formula}` — literal text inside a NESTED f-string
        #      (the CIF content block, itself embedded in the generated
        #      script). repr() doesn't help here: this text becomes part of
        #      the generated script's SOURCE, so a formula containing `"""`
        #      would still terminate that nested string literal early,
        #      corrupting the generated script regardless of how the first
        #      occurrence was escaped. A chemical formula (Fe2O3, SiO2,
        #      NaCl, Ca(OH)2) only ever needs letters, digits, and a few
        #      punctuation marks — stripping to that set is both a
        #      correctness fix (malformed input can't break the generated
        #      script) and a safety one (nothing else can be smuggled
        #      through this path either).
        formula_lit = repr(formula)
        formula_cif_safe = re.sub(r"[^A-Za-z0-9().]", "", formula) or "Unknown"
        output_path_lit = repr(output_path)
        return f'''# Auto-generated Materials Science Synthesizer Script
import sys
import math

formula = {formula_lit}
output_path = {output_path_lit}

print(f"🔬 Synthesizing crystal structure for {{formula}}...")

# PyMatGen / ASE structure generation template
cif_content = f"""# CIF file generated by Autobot Materials Synthesizer
data_{formula_cif_safe}
_cell_length_a       5.431
_cell_length_b       5.431
_cell_length_c       5.431
_cell_angle_alpha    90.00
_cell_angle_beta     90.00
_cell_angle_gamma    90.00
_symmetry_space_group_name_H-M 'F d -3 m'

loop_
_atom_site_label
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
Fe1 0.0000 0.0000 0.0000
O1  0.2500 0.2500 0.2500
"""

with open(output_path, "w", encoding="utf-8") as f:
    f.write(cif_content)

a = 5.431
volume = a ** 3
print(f"✅ Crystal CIF written to: {{output_path}}")
print(f"📊 Unit Cell Volume: {{volume:.3f}} Å³")
'''

    @staticmethod
    def generate_vesta_launch_script(cif_path: str, vesta_exe: str = "VESTA.exe") -> str:
        """
        Generates a launcher script to open the computed CIF file directly in VESTA.
        """
        cif_path_lit = repr(cif_path)
        vesta_exe_lit = repr(vesta_exe)
        return f'''# Auto-generated VESTA Launcher Script
import subprocess
import os

cif_path = {cif_path_lit}
vesta_exe = {vesta_exe_lit}

if os.path.exists(vesta_exe):
    print(f"🚀 Opening {{cif_path}} in VESTA...")
    subprocess.Popen([vesta_exe, cif_path])
else:
    print(f"⚠️ VESTA binary not found at {{vesta_exe}}. Please install VESTA or add to PATH.")
'''
